### ISSUE TITLE
Level up message and rank card bug

### ISSUE THREAD

**Issue by Mini-Ware** [ahnaf-zamil/ayikobot#1]
When sending the command ay.rank with one more message before leveling up, the level up message says that you have reached the next level while the rank card still shows that you are on the previous level.
![ayrankissue](https://user-images.githubusercontent.com/67500556/109981974-67ec9600-7d3c-11eb-9e03-ad411604dda8.png)

**Comment by ahnaf-zamil** [comment]
Got it. Maybe I could just make the level up message wait 1 second before sending. That would give it enough time to update the database entry and then show the card

**Comment by ahnaf-zamil** [comment]
Fixed in commit [02faac7346e3b4d16af11cd27cac36ad8c16126e.](https://github.com/ahnaf-zamil/ayikobot/commit/02faac7346e3b4d16af11cd27cac36ad8c16126e)
